"""fixing a typo on order table

Revision ID: 0ec06c4af27a
Revises: 863db855fb2d
Create Date: 2023-11-28 22:34:44.613837

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0ec06c4af27a'
down_revision = '863db855fb2d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_name', sa.String(length=64), nullable=False))
        batch_op.drop_column('pruduct_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pruduct_name', mysql.VARCHAR(length=64), nullable=False))
        batch_op.drop_column('product_name')

    # ### end Alembic commands ###
