"""Added admin table

Revision ID: 433ac3f22b48
Revises: d3d78d274c25
Create Date: 2023-11-23 00:47:13.093761

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '433ac3f22b48'
down_revision = 'd3d78d274c25'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=128), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('admin')
    # ### end Alembic commands ###
