"""Modifying Cost column of 0rder table to take in consediration 2 numbers after comma

Revision ID: 4a7b25c0d854
Revises: 005be9ec6e51
Create Date: 2023-11-28 14:41:19.532211

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4a7b25c0d854'
down_revision = '005be9ec6e51'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cost', sa.DECIMAL(precision=10, scale=2), nullable=False))
        batch_op.drop_column('product_cost')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_cost', mysql.FLOAT(), nullable=False))
        batch_op.drop_column('cost')

    # ### end Alembic commands ###
