"""Added Order class

Revision ID: 5d37541914c9
Revises: 713631f24445
Create Date: 2023-11-28 14:15:23.423342

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d37541914c9'
down_revision = '713631f24445'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order',
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=64), nullable=False),
    sa.Column('last_name', sa.String(length=64), nullable=False),
    sa.Column('adress', sa.String(length=255), nullable=False),
    sa.Column('city', sa.String(length=64), nullable=False),
    sa.Column('postcode', sa.String(length=28), nullable=False),
    sa.Column('country', sa.String(length=64), nullable=False),
    sa.Column('phone_number', sa.String(length=28), nullable=False),
    sa.Column('pruduct_name', sa.String(length=64), nullable=False),
    sa.Column('product_cost', sa.Float(), nullable=False),
    sa.Column('quantity', sa.String(length=28), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('total', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('order_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order')
    # ### end Alembic commands ###
