"""Change data type of cost column

Revision ID: 713631f24445
Revises: 433ac3f22b48
Create Date: 2023-11-24 21:56:55.029687

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '713631f24445'
down_revision = '433ac3f22b48'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.alter_column('cost',
               existing_type=mysql.FLOAT(),
               type_=sa.DECIMAL(precision=10, scale=2),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.alter_column('cost',
               existing_type=sa.DECIMAL(precision=10, scale=2),
               type_=mysql.FLOAT(),
               existing_nullable=False)

    # ### end Alembic commands ###
