"""initial migration

Revision ID: d9ae9e0767cf
Revises: 
Create Date: 2023-11-30 17:32:39.375340

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9ae9e0767cf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=128), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('order',
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=64), nullable=False),
    sa.Column('last_name', sa.String(length=64), nullable=False),
    sa.Column('adress', sa.String(length=255), nullable=False),
    sa.Column('city', sa.String(length=64), nullable=False),
    sa.Column('postcode', sa.String(length=28), nullable=False),
    sa.Column('country', sa.String(length=64), nullable=False),
    sa.Column('phone_number', sa.String(length=28), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('product_name', sa.String(length=64), nullable=False),
    sa.Column('product_cost', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('quantity', sa.String(length=28), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('total_cost', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.String(length=28), nullable=False),
    sa.PrimaryKeyConstraint('order_id')
    )
    op.create_table('product',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('cost', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('cover', sa.String(length=255), nullable=False),
    sa.Column('photo1', sa.String(length=255), nullable=False),
    sa.Column('photo2', sa.String(length=255), nullable=False),
    sa.Column('photo3', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('product_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product')
    op.drop_table('order')
    op.drop_table('admin')
    # ### end Alembic commands ###
