"""added a flag column on product table

Revision ID: f9090666e986
Revises: d9ae9e0767cf
Create Date: 2023-12-04 21:10:18.539229

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9090666e986'
down_revision = 'd9ae9e0767cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('flag', sa.String(length=28), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('flag')

    # ### end Alembic commands ###
